#!/usr/bin/env bash

# -E: ERR trap is inherited by functions (otherwise failures inside them are ignored)
set -Eeuo pipefail

# Get script directory
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

NAMESPACE="ctos"

# main directories
CONFIG_DIR="/etc/$NAMESPACE"
INSTALL_DIR="/opt/$NAMESPACE"

# configs
GREETER_CONFIG_FILEPATH="$CONFIG_DIR/greeter.config.json"
GREETER_KWIN_FILEPATH="$CONFIG_DIR/greeter.kwin.conf"

# user the installer runs for (also when started via sudo)
INVOKING_USER="${SUDO_USER:-$(id -un)}"

# --no-splash: skip the boot/login splash (splash/install.sh)
INSTALL_SPLASH=1
for arg in "$@"; do
  case $arg in
    --no-splash) INSTALL_SPLASH=0 ;;
    *)
      echo "usage: $0 [--no-splash]" >&2
      exit 1
      ;;
  esac
done

graceful_exit() {
  echo
  echo
  echo -e "[EXIT] Process interrupted or failed."
  exit 1
}

install_dependencies() {
  echo "[DEPS] Checking dependencies..."
  echo

  # all available in the official repositories (extra)
  local packages=(
    "greetd"
    "rsync"
    "python"
    "kwin"
    "quickshell"
    "ttf-jetbrains-mono-nerd"
    "curl"
  )

  # `pacman -T` also accepts packages that provide the dependency (e.g. quickshell-git)
  local missing
  missing=$(pacman -T "${packages[@]}" || true)

  for pkg in "${packages[@]}"; do
    if ! grep -qxF "$pkg" <<<"$missing"; then
      echo "[DEPS]    ok: $pkg"
    fi
  done

  if [[ -n "$missing" ]]; then
    # shellcheck disable=SC2086
    echo "[DEPS] Installing:" $missing
    # shellcheck disable=SC2086
    sudo pacman -S --needed --noconfirm $missing
  fi

  echo
  echo "[DEPS] Done."
  echo
}

# Prints the primary connected monitor name, or nothing
detect_monitor() {
  local monitor=""

  # kscreen-doctor needs the running KDE session; -o output contains ANSI colors, use JSON
  if command -v kscreen-doctor &>/dev/null; then
    monitor=$(kscreen-doctor -j 2>/dev/null | python3 -c '
import json, sys
outputs = [o for o in json.load(sys.stdin)["outputs"] if o["connected"] and o.get("enabled")]
outputs.sort(key=lambda o: o.get("priority") or 99)
print(outputs[0]["name"] if outputs else "")
' 2>/dev/null || true)
  fi

  # fallback: first connected DRM connector
  if [[ -z "$monitor" ]]; then
    local connector
    for connector in /sys/class/drm/card*-*; do
      [[ -f "$connector/status" ]] || continue
      if [[ "$(cat "$connector/status")" == "connected" ]]; then
        monitor=$(basename "$connector")
        monitor=${monitor#card*-}
        break
      fi
    done
  fi

  echo "$monitor"
}

# Merges the existing config (if any) with defaults and prints the result.
# User values are kept; values generated by old installer versions are migrated.
generate_greeter_config() {
  local user="$1"
  local monitor="$2"
  local existing="$3"

  python3 - "$user" "$monitor" "$existing" <<'EOF'
import json, sys

user, monitor, existing_path = sys.argv[1:4]

defaults = {
    "$schema": "https://raw.githubusercontent.com/alexsesser/ctOS/main/schema/greeter.schema.json",
    "user": user,
    "monitor": monitor,
    "fontFamily": "JetBrainsMono Nerd Font",
    "fakeIdentity": {"id": "XYZ-843", "class": "L5_PROV", "fullName": "Blume Admin"},
    "fakeStatus": {"env": "Workstation"},
    "modes": {
        "greetd": {"animations": "all", "launch": ["startplasma-wayland"]},
        "lockd": {"animations": "reduced"},
        "test": {"animations": "all"},
    },
}

def merge(base, override):
    result = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        else:
            result[key] = value
    return result

config = defaults
if existing_path:
    with open(existing_path) as f:
        config = merge(defaults, json.load(f))

# always point to this fork's schema
config["$schema"] = defaults["$schema"]

# exit commands written by old installers are not needed: Greetd.launch() quits
# Quickshell and kwin exits with it (--exit-with-session)
greetd = config.get("modes", {}).get("greetd", {})
if greetd.get("exit") in (["pkill", "kwin_wayland"], ["pkill", "quickshell"]):
    del greetd["exit"]

# NODE shows the real IP address now
config.get("fakeStatus", {}).pop("node", None)

print(json.dumps(config, indent=2, ensure_ascii=False))
EOF
}

generate_kwin_conf() {
  cat <<EOF
#!/bin/sh
# Started by greetd (see /etc/greetd/config.toml). Generated by ctOS install.sh.

# normally set by pam_systemd for the greeter user
export XDG_RUNTIME_DIR="\${XDG_RUNTIME_DIR:-/run/user/\$(id -u)}"
export QT_QPA_PLATFORM=wayland
export GDK_BACKEND=wayland
export CTOS_MODE=greetd

# greetd attaches the greeter to the console (tty1): clear what the boot left
# there and log to the journal (journalctl -t ctos-greeter), otherwise the text
# flashes on screen when kwin exits after login
printf '\\033[2J\\033[3J\\033[H'
exec systemd-cat --identifier=ctos-greeter /usr/bin/kwin_wayland \\
    --exit-with-session="/usr/bin/quickshell --path $INSTALL_DIR/greeter.qml" \\
    --no-lockscreen \\
    --no-global-shortcuts \\
    --no-kactivities
EOF
}

# Writes the file (creates or overwrites)
write_file() {
  local contents="$1"
  local target_path="$2"
  local mode="$3"
  local existed=0

  [[ -f "$target_path" ]] && existed=1

  if [[ -z "$contents" ]]; then
    echo
    echo "[!][ERROR] empty input for $target_path"
    exit 1
  fi

  sudo mkdir -p "$(dirname "$target_path")"
  printf '%s\n' "$contents" | sudo tee "$target_path" >/dev/null
  sudo chmod "$mode" "$target_path"

  if [[ $existed -eq 1 ]]; then
    echo "[ITEM] updated: $target_path"
  else
    echo "[ITEM]   added: $target_path"
  fi
}

run_setup_wizard() {
  echo
  echo "[CTOS INSTALLER — KDE/Arch]"
  echo

  read -rp "[Q] ENTER TARGET USER [$INVOKING_USER]: " SELECTED_USER || true
  SELECTED_USER=${SELECTED_USER:-$INVOKING_USER}

  local default_monitor
  default_monitor=$(detect_monitor)
  local monitor_prompt=${default_monitor:+ [$default_monitor]}
  read -rp "[Q] ENTER PRIMARY MONITOR$monitor_prompt: " SELECTED_MONITOR || true
  SELECTED_MONITOR=${SELECTED_MONITOR:-$default_monitor}

  echo
  echo "[BASIC SETTINGS]"
  echo "COMPOSITOR=kwin_wayland"
  echo "USER=$SELECTED_USER"
  echo "MONITOR=$SELECTED_MONITOR"
  echo

  local reply=""
  read -rp "[Q] Proceed with installation? (y/n) " reply || true

  if [[ ! $reply =~ ^[Yy]$ ]]; then
    echo
    echo "[EXIT] Installation aborted."
    exit 1
  fi
}

install_greeter_config() {
  if [[ -f "$GREETER_CONFIG_FILEPATH" ]]; then
    # update: keep every existing setting, add missing defaults
    local existing_monitor
    existing_monitor=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("monitor", ""))' "$GREETER_CONFIG_FILEPATH")

    local monitor="$existing_monitor"
    if [[ -z "$monitor" ]]; then
      monitor=$(detect_monitor)
    fi

    write_file "$(generate_greeter_config "$INVOKING_USER" "$monitor" "$GREETER_CONFIG_FILEPATH")" "$GREETER_CONFIG_FILEPATH" 644
  else
    run_setup_wizard
    write_file "$(generate_greeter_config "$SELECTED_USER" "$SELECTED_MONITOR" "")" "$GREETER_CONFIG_FILEPATH" 644
  fi
}

install_greeter_kwin_conf() {
  # executable: greetd runs it as a script
  write_file "$(generate_kwin_conf)" "$GREETER_KWIN_FILEPATH" 755
}

# Writable state for the greeter user (its home is /): last known IP address
install_state_dir() {
  local state_dir="/var/lib/$NAMESPACE"

  if ! id greeter &>/dev/null; then
    echo "[WARN] user 'greeter' not found, skipping $state_dir"
    return
  fi

  sudo install -d -o greeter -g greeter -m 755 "$state_dir"
  echo "[ITEM]     ok: $state_dir (owner greeter)"
}

sync_project_files() {
  local existed=0
  [[ -d "$INSTALL_DIR" ]] && existed=1

  sudo mkdir -p "$INSTALL_DIR"

  # --delete: stale files would be loaded by Quickshell (e.g. "ambiguous type")
  # --delete-excluded: also drop files that older installers copied
  sudo rsync -ahq --delete --delete-excluded \
    --exclude="/.git" \
    --exclude="/.assets" \
    --exclude="/.github" \
    --exclude="/.vscode" \
    --exclude="/extras" \
    --exclude="/themes" \
    --exclude="/install.sh" \
    --exclude="/README.md" \
    --exclude="/CLAUDE.md" \
    --exclude="/splash" \
    --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
    "$SCRIPT_DIR/" "$INSTALL_DIR/"

  if [[ $existed -eq 1 ]]; then
    echo "[ITEM] updated: $INSTALL_DIR"
  else
    echo "[ITEM]   added: $INSTALL_DIR"
  fi
}

check_greetd_config() {
  local greetd_config="/etc/greetd/config.toml"

  if [[ ! -f "$greetd_config" ]]; then
    echo
    echo "[WARN] $greetd_config not found. Is greetd installed?"
    echo "       Install with: sudo pacman -S greetd"
    return
  fi

  if grep -q "$GREETER_KWIN_FILEPATH" "$greetd_config"; then
    echo "[ITEM]     ok: greetd configured"
  else
    echo
    echo "[WARN] greetd is not configured to use ctOS."
    echo "       Add to $greetd_config:"
    echo
    echo "  [default_session]"
    echo "  command = \"$GREETER_KWIN_FILEPATH\""
    echo "  user = \"greeter\""
    echo
  fi
}

# --------------------------------------------------------------------------------
# SECTION Main
# --------------------------------------------------------------------------------

trap graceful_exit ERR SIGINT SIGTERM

# ask for the password once, before anything else
sudo -v

install_dependencies

install_greeter_config

echo

install_greeter_kwin_conf

install_state_dir

sync_project_files

check_greetd_config

if [[ $INSTALL_SPLASH -eq 1 ]]; then
  "$SCRIPT_DIR/splash/install.sh"
fi

echo
echo "[EXIT] SUCCESSFULLY COMPLETED."
